### PR TITLE
Stable Build Merge

### PR DESCRIPTION
**Pull request by Recol**
Push for the final iteration of the product review.

### CODE REVIEW

**Review by michael-mcgrattan — COMMENTED** [review]
Code looks great!

**Review by andrewgordonyule — APPROVED** [review]
Approved changes. Agree with the decision to amend the Menu.java class to split storeMenu() into its own method.

**Review by conor-walker — APPROVED** [review]
Yup, happy enough with how it's looking! I think if we wanted to punish ourselves we could go a bit furtherin refacotirng, but I think we're grand as-is :)

**Review by holko95 — APPROVED** [review]
Approved, code looks tidy and clear

**Pull request merged**
